version: "3"
services:
  db:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db-data:/data/postgres

  api:
    build:
      context: ./server
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: always
    ports:
      - 8000:8000
    env_file: .env
    command: 'sh -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"'
    volumes:
      - ./server/:/app
    depends_on:
      - db
      - selenium

  client:
    build:
      context: ./client
    restart: always
    ports:
      - 80:80
    env_file: ./client/.env
    depends_on:
      - api


  queue:
    build:
      context: ./server
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: unless-stopped
    env_file: .env
    command: sh /entrypoint-queue.sh
    volumes:
      - ./server/:/app

  beat:
    build:
      context: ./server
      args:
        REQUIREMENTS_FILE: dev.txt
    restart: unless-stopped
    env_file: .env
    command: sh /entrypoint-beat.sh
    volumes:
      - ./server/:/app

  redis:
    image: redis:alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  db-data:
