# Generated by Django 3.2.3 on 2021-10-08 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('personal_name', models.CharField(blank=True, default='', max_length=100)),
                ('insta_username', models.CharField(blank=True, default='', max_length=100)),
                ('twitter_username', models.CharField(blank=True, default='', max_length=100)),
                ('facebook_username', models.CharField(blank=True, default='', max_length=100)),
                ('linkedin_username', models.CharField(blank=True, default='', max_length=100)),
                ('insta_url', models.TextField()),
                ('twitter_url', models.TextField()),
                ('facebook_url', models.TextField()),
                ('linkedin_url', models.TextField()),
            ],
        ),
    ]
