export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_SIDEBAR = "SET_SIDEBAR";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const RETRIEVE_TWEETS_SUCCESS = "RETRIEVE_TWEETS_SUCCESS";
export const RETRIEVE_TWEETS_FAIL = "RETRIEVE_TWEETS_FAIL";
export const RETRIEVE_TWITTER_PROFILE_SUCCESS = "RETRIEVE_TWITTER_PROFILE_SUCCESS";
export const RETRIEVE_TWITTER_PROFILE_FAIL = "RETRIEVE_TWITTER_PROFILE_FAIL";

export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_FAIL = "REFRESH_TOKEN_FAIL";
export const UNVALID_TOKEN = "UNVALID_TOKEN";

export const RETRIEVE_INSTA_POSTS_SUCCESS = "RETRIEVE_INSTA_POSTS_SUCCESS";
export const RETRIEVE_INSTA_POSTS_FAIL = "RETRIEVE_INSTA_POSTS_FAIL";
export const RETRIEVE_INSTA_PROFILE_SUCCESS = "RETRIEVE_INSTA_PROFILE_SUCCESS";
export const RETRIEVE_INSTA_PROFILE_FAIL = "RETRIEVE_INSTA_PROFILE_FAIL";


export const RETRIEVE_FACEBOOK_PROFILE_SUCCESS = "RETRIEVE_FACEBOOK_PROFILE_SUCCESS";
export const RETRIEVE_FACEBOOK_PROFILE_FAIL = "RETRIEVE_FACEBOOK_PROFILE_FAIL";

export const RETRIEVE_LINKEDIN_PROFILE_SUCCESS = "RETRIEVE_LINKEDIN_PROFILE_SUCCESS";
export const RETRIEVE_LINKEDIN_PROFILE_FAIL = "RETRIEVE_LINKEDIN_PROFILE_FAIL";

export const RETRIEVE_SEARCH_SUCCESS = "RETRIEVE_SEARCH_SUCCESS";
export const RETRIEVE_SEARCH_FAIL = "RETRIEVE_SEARCH_FAIL";